version: "3.9"

services:

  postgres:
    image: postgres:17
    container_name: postgres_voo
    restart: always

    environment:
      POSTGRES_DB: voo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d voo"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ms_voo

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/voo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

    restart: unless-stopped

volumes:
  postgres_data: